name: Fortify Publish SAST Results to GitHub
on:
  workflow_dispatch:

jobs:
  Fortify-Publish:
    # Use the appropriate runner for building your source code
    runs-on: self-hosted
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    env:
      APPLICATION: "${{ github.event.repository.name }}"
      VERSION: "${{ github.ref_name }}"

    steps:
      - name: Export Fortify vulnerability data
        uses: fortify/gha-export-vulnerabilities@v1.0.0
        with:
          ssc_base_url: ${{ vars.FTFY_SSC_URL }}
          ssc_auth_token: ${{ secrets.SSC_UPLOAD_TOKEN }}
          ssc_version_name: ${{ APPLICATION }}:${{ VERSION }}

      # Import Fortify SAST results to GitHub Security Code Scanning
      - name: Import Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./gh-fortify-sast.sarif
