name: Sonatype Nexus IQ Evaluation
on:
  workflow_dispatch:  

jobs:
  nexus-iq-scan:
    runs-on: ubuntu-latest
    env:
      IQ_URL: ${{ secrets.IQ_URL }}
      IQ_TOKEN: ${{ secrets.IQ_TOKEN }}
      IQ_USERNAME: ${{ secrets.IQ_USERNAME }}
      IQ_PASSWORD: ${{ secrets.IQ_PASSWORD }}
      IQ_APP: "petclinic"
      IQ_STAGE: "build"
      IQ_TARGET: "lib"
      
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: ${{ env.IQ_URL }}
        username: ${{ env.IQ_USERNAME }}
        password: ${{ env.IQ_PASSWORD }}
        applicationId: ${{ env.IQ_APP }}
        stage: ${{ env.IQ_STAGE }}
        target: ${{ env.IQ_TARGET }}
