name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Adding markdown
        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
      - name: notice        
        run: echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

  
  Explore-GitHub-Actions-bis:
    runs-on: ubuntu-latest

    steps:
      - name: Adding markdown
        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
      - name: Adding markdown
        run: echo '### Hello again! 🚀' >> $GITHUB_STEP_SUMMARY
