name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Adding markdown
        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
      - name: notice        
        run: echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

  
  Explore-GitHub-Actions-bis:
    runs-on: ubuntu-latest

    steps:
      - name: Adding markdown
        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
      - name: Adding markdown
        run: echo '### Hello again! 🚀' >> $GITHUB_STEP_SUMMARY
